### ISSUE TITLE
Logger freezes when called too many times/Use Log4j instead

### ISSUE THREAD

**Issue by TheGlitch76** [PatchworkMC/patchwork-patcher#25]
Steps to reproduce: 
- Download the server pack for ATM4 and place it in the `input` folder
- Open Patchwork's UI interface, and click "Start Patching"
- Observe Patcher freezes while patching mods (after about 5-10 on my machine)
Workaround:
- Comment out all calls to `LOGGER` in `Patchwork.java`
- Observe Patcher now runs as expected and does not freeze

I recommend using Log4j instead, as our custom logger doesn't seem to provide any extra function that cannot be done with Log4j, Log4j will be on the classpath when running Patcher in Minecraft, and having our own logger system is an excessive maintenance burden.

**Comment by shedaniel** [comment]
Question: Is the logger freezing or the UI freezing?

**Comment by TheGlitch76** [comment]
The logger is blocking the main Patcher thread, not the UI
