### ISSUE TITLE
Find a error

### ISSUE THREAD

**Issue by wdog5** [PatchworkMC/patchwork-patcher#36]
It is a error When I using the patchwork-patcher
[Patchwork/UI] java.nio.file.FileSystemNotFoundException
[Patchwork/UI] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
[Patchwork/UI] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
[Patchwork/UI] 	at java.base/java.nio.file.Path.of(Path.java:208)
[Patchwork/UI] 	at java.base/java.nio.file.Paths.get(Paths.java:98)
[Patchwork/UI] 	at com.patchworkmc.Patchwork.<init>(Patchwork.java:81)
[Patchwork/UI] 	at com.patchworkmc.PatchworkUI.startPatching(PatchworkUI.java:569)
[Patchwork/UI] 	at com.patchworkmc.PatchworkUI.lambda$main$11(PatchworkUI.java:364)
[Patchwork/UI] 	at com.patchworkmc.PatchworkUI.runWithNoExitCall(PatchworkUI.java:420)
[Patchwork/UI] 	at com.patchworkmc.PatchworkUI.lambda$main$13(PatchworkUI.java:362)
[Patchwork/UI] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Patchwork/UI] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Patchwork/UI] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[Patchwork/UI] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[Patchwork/UI] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[Patchwork/UI] 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by wdog5** [comment]
And the module is wetstone,the minecraft version is 1.14.4

**Comment by TheGlitch76** [comment]
Fixed in 976eff1b84ed57ff274fa559d35de7e43ac48308. You'll need to compile it yourself--it's not on the maven.
