### ISSUE TITLE
Level Generators

### ISSUE THREAD

**Issue by valoeghese** [PatchworkMC/patchwork-patcher#40]
Recently, https://github.com/PatchworkMC/patchwork-api/pull/60 got merged.

In order to be able to properly test and apply the functionality of this PR, we need to be able to test it on mods. However this requires patchwork patcher to do some things:

- Make `LevelGeneratorType`s added by forge mods implement `PatchworkLevelGeneratorType`
- Change the constructor invoke to add the `getNextID()` call

- AT the `LevelGeneratorType(ILjava/lang/String;)` constructor to be public (not sure if this is done in patcher or some other thing)

**Comment by coderbot16** [comment]
Seems like this has been sorted out with the merge of https://github.com/PatchworkMC/patchwork-patcher/pull/52
