### ISSUE TITLE
1.16.1, When?

### ISSUE THREAD

**Issue by Fern-Leaves** [PatchworkMC/patchwork-patcher#54]
1.16.1, When?!?!?!?!??!?!?!?!?!?!?!?!?!??!!??!?!?!!!?!?!?!?!??!?!???!??!?!?!?!??!?!?!?!??!??1?//????!?!?!?!?!?

**Comment by florensie** [comment]
Not anytime soon.

**Comment by kitlith** [comment]
To be more specific, patchwork is more or less trying to track a specific commit of Forge LTS. LTS is/was currently 1.14.4, and will be moving to 1.15.2 soonish (if they haven't already) as of time of writing.

Patchwork will probably not be on 1.16 at least until either forge is on 1.17, or patchwork has reimplemented most/all of forge. (and that latter bit is a long way away)
