### ISSUE TITLE
Handle mods referencing ForgeRegistryEntry directly

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-patcher#64]
[Titanium](https://www.curseforge.com/minecraft/mc-mods/titanium) references ForgeRegistryEntry directly: https://github.com/InnovativeOnlineIndustries/Titanium/blob/1.15/src/main/java/com/hrznstudio/titanium/material/ResourceMaterial.java#L52

It should be valid to remap all references of ForgeRegistryEntry to IForgeRegistryEntry, then selectively redirect references to the helper methods elsewhere.

**Comment by TheGlitch76** [comment]
Our approach has changed in API and this is no longer a concern
