### ISSUE TITLE
UI and CLI classes are not found in the main jar or shadow-all jar

### ISSUE THREAD

**Issue by sschr15** [PatchworkMC/patchwork-patcher#88]
In a build using the included gradle wrapper and on the latest commit as of writing this issue (f73eb9249c1ce4ef28cb0d2978aea20df3baf092), UI classes are not found in the non-shadow jar or the `all` jar.

My theory behind this, without much knowledge of gradle workings, is that the `all` and non-shadow jars are compiled using the `main` sourceset and as a result don't contain the UI or CLI classes due to them being in separate sourcesets.

The UI and CLI jars do correctly contain their extra classes and correctly exclude the classes of the opposite type. All jars appear to contain the main classes as intended.

**Comment by sschr15** [comment]
I have created a [modified gzipped jar](https://github.com/PatchworkMC/patchwork-patcher/files/5760891/patchwork-patcher-0.4-SNAPSHOT-all-modified.jar.gz) that has the UI and CLI classes copied into it if anyone would like it.

**Comment by TheGlitch76** [comment]
This is intentional behavior and partially resolved in #85 by not providing the shadow-all
