### ISSUE TITLE
Where is the install application?

### ISSUE THREAD

**Issue by JohnPone** [PatchworkMC/patchwork-patcher#92]
I know this issue has come up before, but I can't find the install application in the jar file. Plus which jar file would I need to download for a single player modpack?

**Comment by IMS212** [comment]
What install application? Patchwork isn't really ready for use outside of a development environment at the moment AFAIK.

**Comment by TheGlitch76** [comment]
1. Patchwork Patcher cannot be "installed", it must be run through gradle or your IDE
2. Read https://github.com/PatchworkMC/patchwork-api#here-be-dragons (We won't help you with basics of running a java program)
